// Liste des pays avec codes et drapeaux
export const COUNTRIES = [
    { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: 'https://flagcdn.com/w20/af.png' },
    { code: 'AX', name: 'Îles Åland', dialCode: '+358', flag: 'https://flagcdn.com/w20/ax.png' },
    { code: 'AL', name: 'Albanie', dialCode: '+355', flag: 'https://flagcdn.com/w20/al.png' },
    { code: 'DZ', name: 'Algérie', dialCode: '+213', flag: 'https://flagcdn.com/w20/dz.png' },
    { code: 'AS', name: 'Samoa américaines', dialCode: '+1684', flag: 'https://flagcdn.com/w20/as.png' },
    { code: 'AD', name: 'Andorre', dialCode: '+376', flag: 'https://flagcdn.com/w20/ad.png' },
    { code: 'AO', name: 'Angola', dialCode: '+244', flag: 'https://flagcdn.com/w20/ao.png' },
    { code: 'AI', name: 'Anguilla', dialCode: '+1264', flag: 'https://flagcdn.com/w20/ai.png' },
    { code: 'AQ', name: 'Antarctique', dialCode: '+672', flag: 'https://flagcdn.com/w20/aq.png' },
    { code: 'AG', name: 'Antigua-et-Barbuda', dialCode: '+1268', flag: 'https://flagcdn.com/w20/ag.png' },
    { code: 'AR', name: 'Argentine', dialCode: '+54', flag: 'https://flagcdn.com/w20/ar.png' },
    { code: 'AM', name: 'Arménie', dialCode: '+374', flag: 'https://flagcdn.com/w20/am.png' },
    { code: 'AW', name: 'Aruba', dialCode: '+297', flag: 'https://flagcdn.com/w20/aw.png' },
    { code: 'AU', name: 'Australie', dialCode: '+61', flag: 'https://flagcdn.com/w20/au.png' },
    { code: 'AT', name: 'Autriche', dialCode: '+43', flag: 'https://flagcdn.com/w20/at.png' },
    { code: 'AZ', name: 'Azerbaïdjan', dialCode: '+994', flag: 'https://flagcdn.com/w20/az.png' },
    { code: 'BS', name: 'Bahamas', dialCode: '+1242', flag: 'https://flagcdn.com/w20/bs.png' },
    { code: 'BH', name: 'Bahreïn', dialCode: '+973', flag: 'https://flagcdn.com/w20/bh.png' },
    { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: 'https://flagcdn.com/w20/bd.png' },
    { code: 'BB', name: 'Barbade', dialCode: '+1246', flag: 'https://flagcdn.com/w20/bb.png' },
    { code: 'BY', name: 'Biélorussie', dialCode: '+375', flag: 'https://flagcdn.com/w20/by.png' },
    { code: 'BE', name: 'Belgique', dialCode: '+32', flag: 'https://flagcdn.com/w20/be.png' },
    { code: 'BZ', name: 'Belize', dialCode: '+501', flag: 'https://flagcdn.com/w20/bz.png' },
    { code: 'BJ', name: 'Bénin', dialCode: '+229', flag: 'https://flagcdn.com/w20/bj.png' },
    { code: 'BM', name: 'Bermudes', dialCode: '+1441', flag: 'https://flagcdn.com/w20/bm.png' },
    { code: 'BT', name: 'Bhoutan', dialCode: '+975', flag: 'https://flagcdn.com/w20/bt.png' },
    { code: 'BO', name: 'Bolivie', dialCode: '+591', flag: 'https://flagcdn.com/w20/bo.png' },
    { code: 'BA', name: 'Bosnie-Herzégovine', dialCode: '+387', flag: 'https://flagcdn.com/w20/ba.png' },
    { code: 'BW', name: 'Botswana', dialCode: '+267', flag: 'https://flagcdn.com/w20/bw.png' },
    { code: 'BR', name: 'Brésil', dialCode: '+55', flag: 'https://flagcdn.com/w20/br.png' },
    { code: 'IO', name: 'Territoire britannique de l’océan Indien', dialCode: '+246', flag: 'https://flagcdn.com/w20/io.png' },
    { code: 'BN', name: 'Brunei Darussalam', dialCode: '+673', flag: 'https://flagcdn.com/w20/bn.png' },
    { code: 'BG', name: 'Bulgarie', dialCode: '+359', flag: 'https://flagcdn.com/w20/bg.png' },
    { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: 'https://flagcdn.com/w20/bf.png' },
    { code: 'BI', name: 'Burundi', dialCode: '+257', flag: 'https://flagcdn.com/w20/bi.png' },
    { code: 'KH', name: 'Cambodge', dialCode: '+855', flag: 'https://flagcdn.com/w20/kh.png' },
    { code: 'CM', name: 'Cameroun', dialCode: '+237', flag: 'https://flagcdn.com/w20/cm.png' },
    { code: 'CA', name: 'Canada', dialCode: '+1', flag: 'https://flagcdn.com/w20/ca.png' },
    { code: 'CV', name: 'Cap-Vert', dialCode: '+238', flag: 'https://flagcdn.com/w20/cv.png' },
    { code: 'KY', name: 'Îles Caïmans', dialCode: '+345', flag: 'https://flagcdn.com/w20/ky.png' },
    { code: 'CF', name: 'République centrafricaine', dialCode: '+236', flag: 'https://flagcdn.com/w20/cf.png' },
    { code: 'TD', name: 'Tchad', dialCode: '+235', flag: 'https://flagcdn.com/w20/td.png' },
    { code: 'CL', name: 'Chili', dialCode: '+56', flag: 'https://flagcdn.com/w20/cl.png' },
    { code: 'CN', name: 'Chine', dialCode: '+86', flag: 'https://flagcdn.com/w20/cn.png' },
    { code: 'CX', name: 'Île Christmas', dialCode: '+61', flag: 'https://flagcdn.com/w20/cx.png' },
    { code: 'CC', name: 'Îles Cocos (Keeling)', dialCode: '+61', flag: 'https://flagcdn.com/w20/cc.png' },
    { code: 'CO', name: 'Colombie', dialCode: '+57', flag: 'https://flagcdn.com/w20/co.png' },
    { code: 'KM', name: 'Comores', dialCode: '+269', flag: 'https://flagcdn.com/w20/km.png' },
    { code: 'CG', name: 'Congo', dialCode: '+242', flag: 'https://flagcdn.com/w20/cg.png' },
    { code: 'CD', name: 'République Démocratique du Congo', dialCode: '+243', flag: 'https://flagcdn.com/w20/cd.png' },
    { code: 'CK', name: 'Îles Cook', dialCode: '+682', flag: 'https://flagcdn.com/w20/ck.png' },
    { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: 'https://flagcdn.com/w20/cr.png' },
    { code: 'CI', name: 'Côte d’Ivoire', dialCode: '+225', flag: 'https://flagcdn.com/w20/ci.png' },
    { code: 'HR', name: 'Croatie', dialCode: '+385', flag: 'https://flagcdn.com/w20/hr.png' },
    { code: 'CU', name: 'Cuba', dialCode: '+53', flag: 'https://flagcdn.com/w20/cu.png' },
    { code: 'CY', name: 'Chypre', dialCode: '+357', flag: 'https://flagcdn.com/w20/cy.png' },
    { code: 'CZ', name: 'République tchèque', dialCode: '+420', flag: 'https://flagcdn.com/w20/cz.png' },
    { code: 'DK', name: 'Danemark', dialCode: '+45', flag: 'https://flagcdn.com/w20/dk.png' },
    { code: 'DJ', name: 'Djibouti', dialCode: '+253', flag: 'https://flagcdn.com/w20/dj.png' },
    { code: 'DM', name: 'Dominique', dialCode: '+1767', flag: 'https://flagcdn.com/w20/dm.png' },
    { code: 'DO', name: 'République dominicaine', dialCode: '+1849', flag: 'https://flagcdn.com/w20/do.png' },
    { code: 'EC', name: 'Équateur', dialCode: '+593', flag: 'https://flagcdn.com/w20/ec.png' },
    { code: 'EG', name: 'Égypte', dialCode: '+20', flag: 'https://flagcdn.com/w20/eg.png' },
    { code: 'SV', name: 'Salvador', dialCode: '+503', flag: 'https://flagcdn.com/w20/sv.png' },
    { code: 'GQ', name: 'Guinée équatoriale', dialCode: '+240', flag: 'https://flagcdn.com/w20/gq.png' },
    { code: 'ER', name: 'Érythrée', dialCode: '+291', flag: 'https://flagcdn.com/w20/er.png' },
    { code: 'EE', name: 'Estonie', dialCode: '+372', flag: 'https://flagcdn.com/w20/ee.png' },
    { code: 'ET', name: 'Éthiopie', dialCode: '+251', flag: 'https://flagcdn.com/w20/et.png' },
    { code: 'FK', name: 'Îles Malouines (Falkland)', dialCode: '+500', flag: 'https://flagcdn.com/w20/fk.png' },
    { code: 'FO', name: 'Îles Féroé', dialCode: '+298', flag: 'https://flagcdn.com/w20/fo.png' },
    { code: 'FJ', name: 'Fidji', dialCode: '+679', flag: 'https://flagcdn.com/w20/fj.png' },
    { code: 'FI', name: 'Finlande', dialCode: '+358', flag: 'https://flagcdn.com/w20/fi.png' },
    { code: 'FR', name: 'France', dialCode: '+33', flag: 'https://flagcdn.com/w20/fr.png' },
    { code: 'GF', name: 'Guyane française', dialCode: '+594', flag: 'https://flagcdn.com/w20/gf.png' },
    { code: 'PF', name: 'Polynésie française', dialCode: '+689', flag: 'https://flagcdn.com/w20/pf.png' },
    { code: 'GA', name: 'Gabon', dialCode: '+241', flag: 'https://flagcdn.com/w20/ga.png' },
    { code: 'GM', name: 'Gambie', dialCode: '+220', flag: 'https://flagcdn.com/w20/gm.png' },
    { code: 'GE', name: 'Géorgie', dialCode: '+995', flag: 'https://flagcdn.com/w20/ge.png' },
    { code: 'DE', name: 'Allemagne', dialCode: '+49', flag: 'https://flagcdn.com/w20/de.png' },
    { code: 'GH', name: 'Ghana', dialCode: '+233', flag: 'https://flagcdn.com/w20/gh.png' },
    { code: 'GI', name: 'Gibraltar', dialCode: '+350', flag: 'https://flagcdn.com/w20/gi.png' },
    { code: 'GR', name: 'Grèce', dialCode: '+30', flag: 'https://flagcdn.com/w20/gr.png' },
    { code: 'GL', name: 'Groenland', dialCode: '+299', flag: 'https://flagcdn.com/w20/gl.png' },
    { code: 'GD', name: 'Grenade', dialCode: '+1473', flag: 'https://flagcdn.com/w20/gd.png' },
    { code: 'GP', name: 'Guadeloupe', dialCode: '+590', flag: 'https://flagcdn.com/w20/gp.png' },
    { code: 'GU', name: 'Guam', dialCode: '+1671', flag: 'https://flagcdn.com/w20/gu.png' },
    { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: 'https://flagcdn.com/w20/gt.png' },
    { code: 'GG', name: 'Guernesey', dialCode: '+44', flag: 'https://flagcdn.com/w20/gg.png' },
    { code: 'GN', name: 'Guinée', dialCode: '+224', flag: 'https://flagcdn.com/w20/gn.png' },
    { code: 'GW', name: 'Guinée-Bissau', dialCode: '+245', flag: 'https://flagcdn.com/w20/gw.png' },
    { code: 'GY', name: 'Guyana', dialCode: '+595', flag: 'https://flagcdn.com/w20/gy.png' },
    { code: 'HT', name: 'Haïti', dialCode: '+509', flag: 'https://flagcdn.com/w20/ht.png' },
    { code: 'VA', name: 'Saint-Siège (Vatican)', dialCode: '+379', flag: 'https://flagcdn.com/w20/va.png' },
    { code: 'HN', name: 'Honduras', dialCode: '+504', flag: 'https://flagcdn.com/w20/hn.png' },
    { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: 'https://flagcdn.com/w20/hk.png' },
    { code: 'HU', name: 'Hongrie', dialCode: '+36', flag: 'https://flagcdn.com/w20/hu.png' },
    { code: 'IS', name: 'Islande', dialCode: '+354', flag: 'https://flagcdn.com/w20/is.png' },
    { code: 'IN', name: 'Inde', dialCode: '+91', flag: 'https://flagcdn.com/w20/in.png' },
    { code: 'ID', name: 'Indonésie', dialCode: '+62', flag: 'https://flagcdn.com/w20/id.png' },
    { code: 'IR', name: 'Iran', dialCode: '+98', flag: 'https://flagcdn.com/w20/ir.png' },
    { code: 'IQ', name: 'Irak', dialCode: '+964', flag: 'https://flagcdn.com/w20/iq.png' },
    { code: 'IE', name: 'Irlande', dialCode: '+353', flag: 'https://flagcdn.com/w20/ie.png' },
    { code: 'IM', name: 'Île de Man', dialCode: '+44', flag: 'https://flagcdn.com/w20/im.png' },
    { code: 'IL', name: 'Israël', dialCode: '+972', flag: 'https://flagcdn.com/w20/il.png' },
    { code: 'IT', name: 'Italie', dialCode: '+39', flag: 'https://flagcdn.com/w20/it.png' },
    { code: 'JM', name: 'Jamaïque', dialCode: '+1876', flag: 'https://flagcdn.com/w20/jm.png' },
    { code: 'JP', name: 'Japon', dialCode: '+81', flag: 'https://flagcdn.com/w20/jp.png' },
    { code: 'JE', name: 'Jersey', dialCode: '+44', flag: 'https://flagcdn.com/w20/je.png' },
    { code: 'JO', name: 'Jordanie', dialCode: '+962', flag: 'https://flagcdn.com/w20/jo.png' },
    { code: 'KZ', name: 'Kazakhstan', dialCode: '+77', flag: 'https://flagcdn.com/w20/kz.png' },
    { code: 'KE', name: 'Kenya', dialCode: '+254', flag: 'https://flagcdn.com/w20/ke.png' },
    { code: 'KI', name: 'Kiribati', dialCode: '+686', flag: 'https://flagcdn.com/w20/ki.png' },
    { code: 'KP', name: 'Corée du Nord', dialCode: '+850', flag: 'https://flagcdn.com/w20/kp.png' },
    { code: 'KR', name: 'Corée du Sud', dialCode: '+82', flag: 'https://flagcdn.com/w20/kr.png' },
    { code: 'KW', name: 'Koweït', dialCode: '+965', flag: 'https://flagcdn.com/w20/kw.png' },
    { code: 'KG', name: 'Kirghizistan', dialCode: '+996', flag: 'https://flagcdn.com/w20/kg.png' },
    { code: 'LA', name: 'Laos', dialCode: '+856', flag: 'https://flagcdn.com/w20/la.png' },
    { code: 'LV', name: 'Lettonie', dialCode: '+371', flag: 'https://flagcdn.com/w20/lv.png' },
    { code: 'LB', name: 'Liban', dialCode: '+961', flag: 'https://flagcdn.com/w20/lb.png' },
    { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: 'https://flagcdn.com/w20/ls.png' },
    { code: 'LR', name: 'Libéria', dialCode: '+231', flag: 'https://flagcdn.com/w20/lr.png' },
    { code: 'LY', name: 'Libye', dialCode: '+218', flag: 'https://flagcdn.com/w20/ly.png' },
    { code: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: 'https://flagcdn.com/w20/li.png' },
    { code: 'LT', name: 'Lituanie', dialCode: '+370', flag: 'https://flagcdn.com/w20/lt.png' },
    { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: 'https://flagcdn.com/w20/lu.png' },
    { code: 'MO', name: 'Macao', dialCode: '+853', flag: 'https://flagcdn.com/w20/mo.png' },
    { code: 'MK', name: 'Macédoine du Nord', dialCode: '+389', flag: 'https://flagcdn.com/w20/mk.png' },
    { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: 'https://flagcdn.com/w20/mg.png' },
    { code: 'MW', name: 'Malawi', dialCode: '+265', flag: 'https://flagcdn.com/w20/mw.png' },
    { code: 'MY', name: 'Malaisie', dialCode: '+60', flag: 'https://flagcdn.com/w20/my.png' },
    { code: 'MV', name: 'Maldives', dialCode: '+960', flag: 'https://flagcdn.com/w20/mv.png' },
    { code: 'ML', name: 'Mali', dialCode: '+223', flag: 'https://flagcdn.com/w20/ml.png' },
    { code: 'MT', name: 'Malte', dialCode: '+356', flag: 'https://flagcdn.com/w20/mt.png' },
    { code: 'MH', name: 'Îles Marshall', dialCode: '+692', flag: 'https://flagcdn.com/w20/mh.png' },
    { code: 'MQ', name: 'Martinique', dialCode: '+596', flag: 'https://flagcdn.com/w20/mq.png' },
    { code: 'MR', name: 'Mauritanie', dialCode: '+222', flag: 'https://flagcdn.com/w20/mr.png' },
    { code: 'MU', name: 'Maurice', dialCode: '+230', flag: 'https://flagcdn.com/w20/mu.png' },
    { code: 'YT', name: 'Mayotte', dialCode: '+262', flag: 'https://flagcdn.com/w20/yt.png' },
    { code: 'MX', name: 'Mexique', dialCode: '+52', flag: 'https://flagcdn.com/w20/mx.png' },
    { code: 'FM', name: 'Micronésie', dialCode: '+691', flag: 'https://flagcdn.com/w20/fm.png' },
    { code: 'MD', name: 'Moldavie', dialCode: '+373', flag: 'https://flagcdn.com/w20/md.png' },
    { code: 'MC', name: 'Monaco', dialCode: '+377', flag: 'https://flagcdn.com/w20/mc.png' },
    { code: 'MN', name: 'Mongolie', dialCode: '+976', flag: 'https://flagcdn.com/w20/mn.png' },
    { code: 'ME', name: 'Monténégro', dialCode: '+382', flag: 'https://flagcdn.com/w20/me.png' },
    { code: 'MS', name: 'Montserrat', dialCode: '+1664', flag: 'https://flagcdn.com/w20/ms.png' },
    { code: 'MA', name: 'Maroc', dialCode: '+212', flag: 'https://flagcdn.com/w20/ma.png' },
    { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: 'https://flagcdn.com/w20/mz.png' },
    { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: 'https://flagcdn.com/w20/mm.png' },
    { code: 'NA', name: 'Namibie', dialCode: '+264', flag: 'https://flagcdn.com/w20/na.png' },
    { code: 'NR', name: 'Nauru', dialCode: '+674', flag: 'https://flagcdn.com/w20/nr.png' },
    { code: 'NP', name: 'Népal', dialCode: '+977', flag: 'https://flagcdn.com/w20/np.png' },
    { code: 'NL', name: 'Pays-Bas', dialCode: '+31', flag: 'https://flagcdn.com/w20/nl.png' },
    { code: 'AN', name: 'Antilles néerlandaises', dialCode: '+599', flag: 'https://flagcdn.com/w20/bq.png' },
    { code: 'NC', name: 'Nouvelle-Calédonie', dialCode: '+687', flag: 'https://flagcdn.com/w20/nc.png' },
    { code: 'NZ', name: 'Nouvelle-Zélande', dialCode: '+64', flag: 'https://flagcdn.com/w20/nz.png' },
    { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: 'https://flagcdn.com/w20/ni.png' },
    { code: 'NE', name: 'Niger', dialCode: '+227', flag: 'https://flagcdn.com/w20/ne.png' },
    { code: 'NG', name: 'Nigéria', dialCode: '+234', flag: 'https://flagcdn.com/w20/ng.png' },
    { code: 'NU', name: 'Niue', dialCode: '+683', flag: 'https://flagcdn.com/w20/nu.png' },
    { code: 'NF', name: 'Île Norfolk', dialCode: '+672', flag: 'https://flagcdn.com/w20/nf.png' },
    { code: 'MP', name: 'Îles Mariannes du Nord', dialCode: '+1670', flag: 'https://flagcdn.com/w20/mp.png' },
    { code: 'NO', name: 'Norvège', dialCode: '+47', flag: 'https://flagcdn.com/w20/no.png' },
    { code: 'OM', name: 'Oman', dialCode: '+968', flag: 'https://flagcdn.com/w20/om.png' },
    { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: 'https://flagcdn.com/w20/pk.png' },
    { code: 'PW', name: 'Palaos', dialCode: '+680', flag: 'https://flagcdn.com/w20/pw.png' },
    { code: 'PS', name: 'Palestine', dialCode: '+970', flag: 'https://flagcdn.com/w20/ps.png' },
    { code: 'PA', name: 'Panama', dialCode: '+507', flag: 'https://flagcdn.com/w20/pa.png' },
    { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', dialCode: '+675', flag: 'https://flagcdn.com/w20/pg.png' },
    { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: 'https://flagcdn.com/w20/py.png' },
    { code: 'PE', name: 'Pérou', dialCode: '+51', flag: 'https://flagcdn.com/w20/pe.png' },
    { code: 'PH', name: 'Philippines', dialCode: '+63', flag: 'https://flagcdn.com/w20/ph.png' },
    { code: 'PN', name: 'Pitcairn', dialCode: '+872', flag: 'https://flagcdn.com/w20/pn.png' },
    { code: 'PL', name: 'Pologne', dialCode: '+48', flag: 'https://flagcdn.com/w20/pl.png' },
    { code: 'PT', name: 'Portugal', dialCode: '+351', flag: 'https://flagcdn.com/w20/pt.png' },
    { code: 'PR', name: 'Porto Rico', dialCode: '+1939', flag: 'https://flagcdn.com/w20/pr.png' },
    { code: 'QA', name: 'Qatar', dialCode: '+974', flag: 'https://flagcdn.com/w20/qa.png' },
    { code: 'RO', name: 'Roumanie', dialCode: '+40', flag: 'https://flagcdn.com/w20/ro.png' },
    { code: 'RU', name: 'Russie', dialCode: '+7', flag: 'https://flagcdn.com/w20/ru.png' },
    { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: 'https://flagcdn.com/w20/rw.png' },
    { code: 'RE', name: 'Réunion', dialCode: '+262', flag: 'https://flagcdn.com/w20/re.png' },
    { code: 'BL', name: 'Saint-Barthélemy', dialCode: '+590', flag: 'https://flagcdn.com/w20/bl.png' },
    { code: 'SH', name: 'Sainte-Hélène', dialCode: '+290', flag: 'https://flagcdn.com/w20/sh.png' },
    { code: 'KN', name: 'Saint-Kitts-et-Nevis', dialCode: '+1869', flag: 'https://flagcdn.com/w20/kn.png' },
    { code: 'LC', name: 'Sainte-Lucie', dialCode: '+1758', flag: 'https://flagcdn.com/w20/lc.png' },
    { code: 'MF', name: 'Saint-Martin (partie française)', dialCode: '+590', flag: 'https://flagcdn.com/w20/mf.png' },
    { code: 'PM', name: 'Saint-Pierre-et-Miquelon', dialCode: '+508', flag: 'https://flagcdn.com/w20/pm.png' },
    { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', dialCode: '+1784', flag: 'https://flagcdn.com/w20/vc.png' },
    { code: 'WS', name: 'Samoa', dialCode: '+685', flag: 'https://flagcdn.com/w20/ws.png' },
    { code: 'SM', name: 'Saint-Marin', dialCode: '+378', flag: 'https://flagcdn.com/w20/sm.png' },
    { code: 'ST', name: 'Sao Tomé-et-Principe', dialCode: '+239', flag: 'https://flagcdn.com/w20/st.png' },
    { code: 'SA', name: 'Arabie saoudite', dialCode: '+966', flag: 'https://flagcdn.com/w20/sa.png' },
    { code: 'SN', name: 'Sénégal', dialCode: '+221', flag: 'https://flagcdn.com/w20/sn.png' },
    { code: 'RS', name: 'Serbie', dialCode: '+381', flag: 'https://flagcdn.com/w20/rs.png' },
    { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: 'https://flagcdn.com/w20/sc.png' },
    { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: 'https://flagcdn.com/w20/sl.png' },
    { code: 'SG', name: 'Singapour', dialCode: '+65', flag: 'https://flagcdn.com/w20/sg.png' },
    { code: 'SK', name: 'Slovaquie', dialCode: '+421', flag: 'https://flagcdn.com/w20/sk.png' },
    { code: 'SI', name: 'Slovénie', dialCode: '+386', flag: 'https://flagcdn.com/w20/si.png' },
    { code: 'SB', name: 'Îles Salomon', dialCode: '+677', flag: 'https://flagcdn.com/w20/sb.png' },
    { code: 'SO', name: 'Somalie', dialCode: '+252', flag: 'https://flagcdn.com/w20/so.png' },
    { code: 'ZA', name: 'Afrique du Sud', dialCode: '+27', flag: 'https://flagcdn.com/w20/za.png' },
    { code: 'SS', name: 'Soudan du Sud', dialCode: '+211', flag: 'https://flagcdn.com/w20/ss.png' },
    { code: 'GS', name: 'Géorgie du Sud-et-les Îles Sandwich du Sud', dialCode: '+500', flag: 'https://flagcdn.com/w20/gs.png' },
    { code: 'ES', name: 'Espagne', dialCode: '+34', flag: 'https://flagcdn.com/w20/es.png' },
    { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: 'https://flagcdn.com/w20/lk.png' },
    { code: 'SD', name: 'Soudan', dialCode: '+249', flag: 'https://flagcdn.com/w20/sd.png' },
    { code: 'SR', name: 'Suriname', dialCode: '+597', flag: 'https://flagcdn.com/w20/sr.png' },
    { code: 'SJ', name: 'Svalbard et Jan Mayen', dialCode: '+47', flag: 'https://flagcdn.com/w20/sj.png' },
    { code: 'SZ', name: 'Eswatini', dialCode: '+268', flag: 'https://flagcdn.com/w20/sz.png' },
    { code: 'SE', name: 'Suède', dialCode: '+46', flag: 'https://flagcdn.com/w20/se.png' },
    { code: 'CH', name: 'Suisse', dialCode: '+41', flag: 'https://flagcdn.com/w20/ch.png' },
    { code: 'SY', name: 'Syrie', dialCode: '+963', flag: 'https://flagcdn.com/w20/sy.png' },
    { code: 'TW', name: 'Taïwan', dialCode: '+886', flag: 'https://flagcdn.com/w20/tw.png' },
    { code: 'TJ', name: 'Tadjikistan', dialCode: '+992', flag: 'https://flagcdn.com/w20/tj.png' },
    { code: 'TZ', name: 'Tanzanie', dialCode: '+255', flag: 'https://flagcdn.com/w20/tz.png' },
    { code: 'TH', name: 'Thaïlande', dialCode: '+66', flag: 'https://flagcdn.com/w20/th.png' },
    { code: 'TL', name: 'Timor oriental', dialCode: '+670', flag: 'https://flagcdn.com/w20/tl.png' },
    { code: 'TG', name: 'Togo', dialCode: '+228', flag: 'https://flagcdn.com/w20/tg.png' },
    { code: 'TK', name: 'Tokelau', dialCode: '+690', flag: 'https://flagcdn.com/w20/tk.png' },
    { code: 'TO', name: 'Tonga', dialCode: '+676', flag: 'https://flagcdn.com/w20/to.png' },
    { code: 'TT', name: 'Trinité-et-Tobago', dialCode: '+1868', flag: 'https://flagcdn.com/w20/tt.png' },
    { code: 'TN', name: 'Tunisie', dialCode: '+216', flag: 'https://flagcdn.com/w20/tn.png' },
    { code: 'TR', name: 'Turquie', dialCode: '+90', flag: 'https://flagcdn.com/w20/tr.png' },
    { code: 'TM', name: 'Turkménistan', dialCode: '+993', flag: 'https://flagcdn.com/w20/tm.png' },
    { code: 'TC', name: 'Îles Turques-et-Caïques', dialCode: '+1649', flag: 'https://flagcdn.com/w20/tc.png' },
    { code: 'TV', name: 'Tuvalu', dialCode: '+688', flag: 'https://flagcdn.com/w20/tv.png' },
    { code: 'UG', name: 'Ouganda', dialCode: '+256', flag: 'https://flagcdn.com/w20/ug.png' },
    { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: 'https://flagcdn.com/w20/ua.png' },
    { code: 'AE', name: 'Émirats arabes unis', dialCode: '+971', flag: 'https://flagcdn.com/w20/ae.png' },
    { code: 'GB', name: 'Royaume-Uni', dialCode: '+44', flag: 'https://flagcdn.com/w20/gb.png' },
    { code: 'US', name: 'États-Unis', dialCode: '+1', flag: 'https://flagcdn.com/w20/us.png' },
    { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: 'https://flagcdn.com/w20/uy.png' },
    { code: 'UZ', name: 'Ouzbékistan', dialCode: '+998', flag: 'https://flagcdn.com/w20/uz.png' },
    { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: 'https://flagcdn.com/w20/vu.png' },
    { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: 'https://flagcdn.com/w20/ve.png' },
    { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: 'https://flagcdn.com/w20/vn.png' },
    { code: 'VG', name: 'Îles Vierges britanniques', dialCode: '+1284', flag: 'https://flagcdn.com/w20/vg.png' },
    { code: 'VI', name: 'Îles Vierges des États-Unis', dialCode: '+1340', flag: 'https://flagcdn.com/w20/vi.png' },
    { code: 'WF', name: 'Wallis-et-Futuna', dialCode: '+681', flag: 'https://flagcdn.com/w20/wf.png' },
    { code: 'YE', name: 'Yémen', dialCode: '+967', flag: 'https://flagcdn.com/w20/ye.png' },
    { code: 'ZM', name: 'Zambie', dialCode: '+260', flag: 'https://flagcdn.com/w20/zm.png' },
    { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: 'https://flagcdn.com/w20/zw.png' }
];
